### PR TITLE
Edits

### PR DESCRIPTION
**Pull request by Gamr13**
Changes list:

jailbreaking.html:
- Added A5 - A11 tip for Checkra1n.

legacyjailbreak.html:
- Added Checkra1n to the list of iOS 12 jailbreaks.

CSS:
- Edited the banner colour from #1abc9c to #0053a1.
- Added matching footer colour for consistency.

signingservices.html:
- Added Signum to the list of paid signing services.

Repo:
- Removed .DS_Store, CNAME and /images/.DS_Store.
- Add .gitignore to ignore .DS_Store files.

Edit: Includes all changes from @QuixThe2nd in PR #1

### CODE REVIEW

**Comment by dallasco** [comment]
Two things - 

CNAME file must remain as it redirects the github pages site to google domains

this pull request has conflicts in signingservices.html
-I'm new to working with pull requests so I cant seem to resolve the conflict. 

appreciate the edits and want to merge this right away if I can get past those two issues

**Comment by Gamr13** [comment]
Sorry, it looks like I didn't remove CNAME at all, not even the .DS_Store files, so I deleted those (as they're just leftover junk files from macOS).

What's the conflict in signingservices? I'll fix it right away :)

**Comment by dallasco** [comment]
fixed it, merged :)

**Comment by Gamr13** [comment]
I hope to contribute more down the road, thanks for starting this project!

**Comment by dallaslittle** [comment]
No problem thank you! And I appreciate your contributions :)

**Pull request merged**
